version: "2"
services:
  vehicle-robot-host:
    image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: "true"
      project.description: ${PROJECT_DESCRIPTION}
      project.group: ${PROJECT_GROUP}
      project.name: ${PROJECT_NAME}
      project.version: ${PROJECT_VERSION}
    environment:
      GOENV: ${GOENV}
      S_ROBOTCLIENT_NODEKEY: ${S_ROBOTCLIENT_NODEKEY}
      S_ROBOTCLIENT_REMOTEADDR: ${S_ROBOTCLIENT_REMOTEADDR}
    dns_search:
    - rancher.internal
    dns:
    - 169.254.169.250
